AWSTemplateFormatVersion: '2010-09-09'
Transform: [EchoMacro, AWS::Serverless-2016-10-31]
Description: >
    dynamodb-event-reader
    Sample SAM Template for dynamodb-event-reader to interact with DynamoDB Events.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 5

Parameters:
  S3Location:
    Type: String
    Default: 's3://mn-w5-8436/macro.yaml'
    Description: The S3 location of template changes 

Resources:
    ReadDynamoDBEvent:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: read_dynamodb_event/
            Handler: app.lambda_handler
            Runtime: python3.7
            Events:
                DynamoDBEvent:
                    Type: DynamoDB # More info about DynamoDB Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#dynamodb
                    Properties:
                        Stream:
                            !GetAtt DynamoDBTable.StreamArn
                        StartingPosition: TRIM_HORIZON
                        BatchSize: 10

    DynamoDBTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            StreamSpecification:
                StreamViewType: NEW_AND_OLD_IMAGES
            ProvisionedThroughput:
                WriteCapacityUnits: 5
                ReadCapacityUnits: 5
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - KeyType: HASH
                  AttributeName: id
