AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Echo macro
Resources:
  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: EchoMacro
      FunctionName: !GetAtt EchoMacroFunction.Arn
  EchoMacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: index.handler
      Runtime: python3.6
      Timeout: 5
